### ISSUE TITLE
nboard pass not parsed

### ISSUE THREAD

**Issue by d7urban** [okuhara/edax-reversi-AVX#1]
I added Edax to the Nboard GUI, but passing threw an error "Illegal move from engine: PA/-64"
To be clear, I passed, then the error popup.

Output from Edax:

> > pong 102
>> ()PongResponse{pong=102}
> status Edax is thinking
>> ()status Edax is thinking
> nodestats 135948 0.00
>> ()(pong=102) nodestats 135948 0.000
> === b7 64.00 0.0
>> ()status
>> ()MoveResponse{pong=102, mli=B7/64.00}
> status Edax is waiting
>> ()status Edax is waiting
<< (Analysis) hint 4
> hint 4 from 8 --------*----*--******--******--**O****-*O*O*---*OOOO*--OOOOOO-- *
>> (Analysis)status Thinking...
< search PA NaN,NaN 0 12
>> (Analysis)search PA NaN,NaN 0 12
>> (Analysis)status
<< () go

< set game (;GM[Othello]PC[NBoard]DT[2022-01-17 12:52:30 GMT]PB[d7urb]PW[Edax24]RE[?]TI[5:00]TY[8]BO[8 ---------------------------O*------*O--------------------------- *]B[F5//2.449]W[D6/0.00]B[C5//1.264]W[F4/1.00]B[D3//1.338]W[E3/2.00]B[F2//4.405]W[C6/9.00]B[G5//6.25]W[B5/13.00]B[A5//3.262]W[B4/23.00]B[B3//5.586]W[C4/25.00/0.1]B[C3//1.75]W[A6/24.00/0.1]B[A7//4.652]W[A3/27.00/0.1]B[F3//2.7680000000000002]W[E6/27.00/0.1]B[C7//4.2860000000000005]W[B6/39.00]B[D7//1.676]W[D8/46.00]B[B8//1.8980000000000001]W[E7/44.00]B[F7//3.689]W[E8/58.00]B[C8//1.793]W[A8/62.00/0.1]B[A4//2.177]W[F8/62.00]B[A2//6.807]W[B7/64.00]B[PA//3.107];)
< ping 104
< go

> pong 104
>> ()PongResponse{pong=104}
> status Edax is thinking
>> ()status Edax is thinking
> nodestats 51415 0.00
>> ()(pong=104) nodestats 51415 0.000
> === pa -64.00 0.0
>> ()status
>> ()MoveResponse{pong=104, mli=PA/-64.00}
> status Edax is waiting
>> ()status Edax is waiting

**Comment by okuhara** [comment]
Fixed in f33d573be527c2c879bf5cc956c6faef950c4008.
