### ISSUE TITLE
leafで最善手が登録されないバグ

### ISSUE THREAD

**Issue by mak-lesdis** [okuhara/edax-reversi-AVX#2]
元のedaxからあるバグなのか私には判別がつかないのですが、最近edax+tlb内のwEdax-x64-modernを使い始めてから認識した現象なので、こちらに共有させていただきます。

内容は、leafとして登録される手が最善ではない手が登録され、結果間違ったbook値になるというものです。

bookはlevel30, depth40にしてb deviateでbookを拡張していました。
問題の局面のbook値と評価値を、edaxのbookをEgaroucidに取り込むことでEgaroucid上で表示しましたのでスクリーンショットを共有します。(ターミナルのedax CUI上でも同じbook値であることは確認しております。）

局面1 （棋譜 f5d6c3d3c4f4f6f3e6e7d7g6f8f7g5h6h4g4h3g3h5h2d2d8g8e8c8c5c6b3b4e3c2a4e2b6a5a3g7）
![スクリーンショット 2023-08-19 070438](https://github.com/okuhara/edax-reversi-AVX/assets/109634544/2eb002cb-d490-4e2f-9b42-857f176941a5)

局面2 （局面1から一手進んでA6と打った局面）
![スクリーンショット 2023-08-19 070430](https://github.com/okuhara/edax-reversi-AVX/assets/109634544/7230cdb5-7ef7-49c2-90de-cf344c05af30)

御覧のように局面2の最善手は(f2 +8)のですので、本来はbook(leaf)としてb5でなくf2が登録されるべきで、局面1のa6は-8であるべきです。
同様の現象を最近edax+tlb内のwEdax-x64-modernを使い始めてから何度か遭遇しております。

**Comment by okuhara** [comment]
たとえば
>b new 35 40
>play f5d6c3d3c4f4f6f3e6e7d7g6f8f7g5h6h4g4h3g3h5h2d2d8g8e8c8c5c6b3b4e3c2a4e2b6a5a3g7a6b5
>b store
>undo
>undo
>hint 10

とかでは問題は起きませんでした。
b subtree とかで問題の起こる book の一部分を切り出すことができれば、それを送ってもらい、原因を調べることはできると思いますが、もしそれが book が壊れていることに起因しているということになった場合は、それが発生した真の原因まではわからないかもしれません。

**Comment by mak-lesdis** [comment]
お返事ありがとうございます。

先ほど、もう一度この時のedaxのbookのバックアップを読み込み、wEdax-x64-modern上でb showを用いて見たのですが、矛盾が見当たりませんでした。

もしかしたら
> (ターミナルのedax CUI上でも同じbook値であることは確認しております。）

この確認に問題があったかもしれません。
こちらもちゃんとスクリーンショットで証左を残すべきでした。

可能性として、今回の問題はedaxのbookに問題があったというよりも、Egaroucidにedaxのbookを取り込んだ際に生じたバグだったのかもしれません。

今回お忙しいところ、お手を煩わせてしまい、すいませんでした。

**Comment by mak-lesdis** [comment]
ご対応ありがとうございました。
