### ISSUE TITLE
flip_sse.c ひとつにしたバージョン

### ISSUE THREAD

**Issue by acepck** [okuhara/edax-reversi-AVX#5]
[flip_sse.txt](https://github.com/user-attachments/files/17533354/flip_sse.txt)

okuharaさんの一つにまとめたflip関数に触発されて作ったものの内のSSE2バージョンです
別のファイルにしての組み込み方が分からなかったのでflip_sse.cとboard.hを上書きで書き換えました
penDでclang gcc共に遅くなりcore2ではclangで遅くなりgccでは少し速くなり
ivybridgeではclang core2共に少し速くなるという微妙で速さではありますが

以前は片側を上下反転させてやっていたのですがここ数日そのままやってみるのを作ってみたら
一部で64個バージョンより少し速くなりました
それぞれの方向について色々やり方がありそうな気がするのでまだ速くできそうな気もします
良かったら試してみて下さい

**Comment by acepck** [comment]
[flip_sse7.txt](https://github.com/user-attachments/files/17560677/flip_sse7.txt)
命令の順番や書き方を変えてみたら命令数が減って少し速くなりました

**Comment by acepck** [comment]
[flip_sse8.txt](https://github.com/user-attachments/files/17589644/flip_sse8.txt)
メモリの使用量を減らしてレイアウトを変えたら少し速くなりました

**Comment by okuhara** [comment]
コメントを追記し（正しいかどうか自信がありませんが）、
e663960b44dba07665cbe95e3dff10e668f66fac
に flip_sse_acepck.c として取り込みました。
SSE バージョンの主な用途は古い CPU かと思いますので、デフォルトにはしませんが、64マスにばらした SSE 版にも使えるテクニックがあるかもしれないので、もう少し検討してみます。
